<script setup lang="ts">
import OpsDialog from '../../../components/ops/OpsDialog.vue';
import AsyncState from '../../../components/ops/AsyncState.vue';
import type { FinancialFactDetail } from '../types/financialReview';

defineProps<{ fact?: FinancialFactDetail; loading: boolean; error: string | null }>();
const emit = defineEmits<{ close: []; retry: [] }>();
</script>

<template>
    <OpsDialog title-id="financial-fact-detail-title" panel-class="max-w-3xl" @close="emit('close')">
        <div class="flex items-start justify-between gap-4"><div><p class="text-xs font-semibold uppercase tracking-wide text-hissa-action">Financial Review</p><h2 id="financial-fact-detail-title" class="mt-1 text-xl font-semibold">Fact lineage</h2></div><button type="button" aria-label="Close detail" class="rounded-lg px-2 py-1 text-2xl leading-none text-hissa-secondary hover:bg-hissa-subtle" @click="emit('close')">×</button></div>
        <AsyncState v-if="loading" state="loading" title="Loading lineage" message="Fetching source, context, mapping, and validation links." />
        <AsyncState v-else-if="error" state="error" title="Lineage could not be loaded" :message="error"><template #action><button type="button" class="rounded-lg bg-hissa-action px-3 py-2 text-sm font-semibold text-white" @click="emit('retry')">Try again</button></template></AsyncState>
        <div v-else-if="fact" class="mt-5 max-h-[68vh] space-y-5 overflow-y-auto pr-1"><section class="grid gap-3 rounded-lg bg-hissa-subtle p-4 sm:grid-cols-3"><div><dt class="text-xs text-hissa-secondary">Fact ID</dt><dd class="mt-1 break-all font-mono text-xs">{{ fact.normalizedFactId }}</dd></div><div><dt class="text-xs text-hissa-secondary">Value</dt><dd class="mt-1 font-mono">{{ fact.value ?? 'Unknown' }} {{ fact.currency ?? '' }}</dd></div><div><dt class="text-xs text-hissa-secondary">Filing</dt><dd class="mt-1 text-sm">{{ fact.filing?.issuerCode ?? 'Unknown' }} · {{ fact.filing?.fiscalPeriod ?? 'Unknown' }}</dd></div></section><section><h3 class="font-semibold">Source fact</h3><dl class="mt-2 grid gap-3 text-sm sm:grid-cols-2"><div><dt class="text-xs text-hissa-secondary">Concept</dt><dd>{{ fact.rawFact?.sourceConcept ?? fact.sourceConcept }}</dd></div><div><dt class="text-xs text-hissa-secondary">Namespace</dt><dd>{{ fact.rawFact?.sourceNamespace ?? 'Unknown' }}</dd></div><div><dt class="text-xs text-hissa-secondary">Context</dt><dd>{{ fact.rawFact?.context?.contextId ?? 'Unknown' }}</dd></div><div><dt class="text-xs text-hissa-secondary">Unit</dt><dd>{{ fact.rawFact?.unit?.measure ?? fact.currency ?? 'Unknown' }}</dd></div></dl></section><section><h3 class="font-semibold">Mapping</h3><p class="mt-2 text-sm text-hissa-secondary">{{ fact.mapping ? `${fact.mapping.canonicalConcept} · version ${fact.mapping.ruleVersion} · ${fact.mapping.status}` : 'No applicable mapping. This fact remains unmapped.' }}</p><p v-if="fact.mapping?.rationale" class="mt-1 text-sm">{{ fact.mapping.rationale }}</p></section><section><h3 class="font-semibold">Validation history</h3><p v-if="fact.validationResults.length === 0" class="mt-2 text-sm text-hissa-secondary">No validation results linked to this fact.</p><ul v-else class="mt-2 space-y-2"><li v-for="result in fact.validationResults" :key="result.validationResultId" class="rounded-lg border border-hissa-border p-3 text-sm"><div class="flex flex-wrap items-center justify-between gap-2"><span class="font-semibold">{{ result.ruleCode }}</span><span>{{ result.result }} · {{ result.severity }}</span></div><p v-if="result.message" class="mt-1 text-hissa-secondary">{{ result.message }}</p></li></ul></section></div>
    </OpsDialog>
</template>
